language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- npm run build
#- npm test
before_install:
- openssl aes-256-cbc -K $encrypted_9ae61cbea87f_key -iv $encrypted_9ae61cbea87f_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build/ morj.services.buyvm.net:/usr/share/nginx/landing/overlay
  on:
    branch: master